########################################################################
#### Meine Polybar-Config.ini
########################################################################
#### Stand: 220119

[global/wm]
;https://github.com/jaagr/polybar/wiki/Configuration#global-wm-settings
margin-top = 0
margin-bottom = 0

include-file = ~/.config/bspwm/polybar/colors/my-colors.ini
include-file = ~/.config/bspwm/polybar/modules.ini


[settings]
;https://github.com/jaagr/polybar/wiki/Configuration#application-settings
throttle-output = 5
throttle-output-for = 10
screenchange-reload = true
compositing-background = over
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

; Define fallback values used by all module formats
format-foreground = #d7dde8
format-background = #2d333f
;format-underline = #3a4151
format-overline =
format-spacing =
format-padding =
format-margin =
format-offset =

################################################################################
################################################################################
############                  MAINBAR-BSPWM                         ############
################################################################################
################################################################################

[bar/mainbar]
monitor = ${env:MONITOR}
;monitor-fallback = HDMI1
width = 100%
height = 30
;offset-x = 1%
;offset-y = 1%
radius = 0.0
fixed-center = true
bottom = false
;separator = |

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2
line-color = ${colors.foreground}

wm-restack = bspwm
override-redirect = true

; Enable support for inter-process messaging
; See the Messaging wiki page for more details.
enable-ipc = true

border-size = 3
;border-left-size = 0
;border-right-size = 25
;border-top-size = 0
;border-bottom-size = 25
border-color = #3a4151

padding-left = 0
padding-right = 1

module-margin-left = 3
module-margin-right = 3

;https://github.com/jaagr/polybar/wiki/Fonts
font-0 = "Noto Sans:size=10;0"
font-1 = "FontAwesome:size=12;1"
font-2 = "Noto Sans:size=11;1"
font-3 = "Noto Sans Mono:size=12;0"
font-4 = "FontAwesome:size=10;0"
font-5 = "Iosevka Term:size=15;1"
font-6 = "Iosevka Term:pixelsize=6;1"

modules-left = bspwm xwindow
modules-center = wifi 
#modules-center = time
#modules-right =  mpd filesystem wifi pulseaudio battery
#modules-right =  netspeed wifi filesystem battery caps num 
modules-right = netspeed filesystem battery caps num time
#modules-right =  networkspeedup networkspeeddown wifi filesystem pulseaudio battery

tray-detached = false
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 1
tray-maxsize = 20
tray-scale = 1.0
tray-position = right
tray-background = ${colors.background}
tray-foreground = ${colors.foreground}

scroll-up = bspwm-desknext
scroll-down = bspwm-deskprev

