# COLORS FOR THE BAR
#Theme name : dtos GruvBoxdark 
def init_colors():
    return [
	    ["#282828", "#282828"], # color 0
            ["#282828", "#282828"], # color 1
            ["#ebdbb2", "#ebdbb2"], # color 2
            ["#000000", "#000000"], # color 3
            ["#fb4934", "#fb4934"], # color 4
            ["#98971a", "#98971a"], # color 5
            ["#d79921", "#d79921"], # color 6
            ["#83a598", "#83a598"], # color 7
            ["#d3869b", "#d3869b"], # color 8
            ["#b8bb26", "#b8bb26"] # color 9
	    ]

colors = init_colors()
