# COLORS FOR THE BAR
#Theme name : dtos Solarizeddark
def init_colors():
    return [
	    ["#002b36", "#002b36"], # color 0
            ["#002b36", "#002b36"], # color 1
            ["#839496", "#839496"], # color 2
            ["#073642", "#073642"], # color 3
            ["#dc322f", "#dc322f"], # color 4
            ["#859900", "#859900"], # color 5
            ["#b58900", "#b58900"], # color 6
            ["#268bd2", "#268bd2"], # color 7
            ["#d33682", "#d33682"], # color 8
            ["#2aa198", "#2aa198"] # color 9
	    ]

colors = init_colors()
