#!/usr/bin/env bash
##   _______  _______ _______ ___ ___ ___ ___  
##  |   _   \|   _   |   _   |   Y   |   Y   | 
##  |.  1   /|   1___|.  1   |.  |   |.      | 
##  |.  _   \|____   |.  ____|. / \  |. \_/  | 
##  |:  1    |:  1   |:  |   |:      |:  |   | 
##  |::.. .  |::.. . |::.|   |::.|:. |::.|:. | 
##  `-------'`-------`---'   `--- ---`--- ---' 
##	Stand: 04.12.21

#+++ Umgebungsvariablen festlegen
export PATH="${PATH}:$HOME/.config/bspwm/bin"

#+++ Autostart
$HOME/.config/bspwm/autostart.sh

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '漣'
		let name++
	done
}
workspaces

bspc config border_width         3
bspc config window_gap           5
bspc config split_ratio          0.50

bspc config focused_border_color "#7aa2f7"
bspc config normal_border_color "#32344a"
bspc config active_border_color "#444b6a"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

##+++Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*


# workspace 1 (Terminals)
declare -a terminal=(Alacritty Xfce4-terminal urxvt)
for i in ${terminal[@]}; do
    bspc rule -a $i desktop='^1' follow=on focus=on; done

# workspace 2 (web)
declare -a web=(firefox discord)
for i in ${web[@]}; do
    bspc rule -a $i desktop='^2' follow=on focus=on; done

# workspace 3 (Files)
declare -a filem=(Thunar Pcmanfm qBittorrent)
for i in ${filem[@]}; do
    bspc rule -a $i desktop='^3' follow=on focus=on; done

# workspace 4 (Text Editor)
declare -a code=(Code Geany emacs)
for i in ${code[@]}; do
    bspc rule -a $i desktop='^4' follow=on focus=on; done

# workspace 5 (Media)
declare -a media=(vlc obs mpv mplayer lxmusic Gimp Gimp-2.10 \
"VirtualBox Manager")
for i in ${media[@]}; do
    bspc rule -a $i desktop='^5' follow=on focus=on; done

# workspace 6 (Communication)
declare -a comm=(Thunderbird TelegramDesktop Hexchat)
for i in ${comm[@]}; do
   bspc rule -a $i desktop='^6' follow=on focus=on; done


# workspace 7 (Settings)
declare -a settings=(GParted Lxappearance Lxtask Lxrandr Arandr \
Pavucontrol Xfce4-settings-manager)
for i in ${settings[@]}; do
    bspc rule -a $i desktop='^7' follow=on focus=on; done

# floating windows
declare -a floats=(Alafloat Lxappearance Arandr \
Viewnior Pcmanfm feh Nm-connection-editor Matplotlib Yad)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done
