#!/bin/sh
##   _______  _______ _______ ___ ___ ___ ___
##  |   _   \|   _   |   _   |   Y   |   Y   |
##  |.  1   /|   1___|.  1   |.  |   |.      |
##  |.  _   \|____   |.  ____|. / \  |. \_/  |
##  |:  1    |:  1   |:  |   |:      |:  |   |
##  |::.. .  |::.. . |::.|   |::.|:. |::.|:. |
##  `-------'`-------`---'   `--- ---`--- ---'
##	Stand: 12.02.22

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh

#BSPWM configuration
#bspc config border_radius       8
bspc config border_width         1
bspc config window_gap           3

bspc config top_padding          34
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      false

#bspc config click_to_focus       true
bspc config split_ratio          0.50
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#a2bd8b"
bspc config focused_border_color	"#cf866f"
bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"


#Single monitor
bspc monitor -d web file text media game sys
#bspc monitor -d 1 2 3 4 5 6
#bspc monitor -d 1 2 3 4 5 6 7 8 9 10

##+++Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

# workspace 1 (web)
declare -a web=(firefox)
for i in ${web[@]}; do
    bspc rule -a $i desktop='^1' follow=on focus=on; done
declare -a comm=(Thunderbird TelegramDesktop Bluemail)
for i in ${comm[@]}; do
   bspc rule -a $i desktop='^1' follow=on focus=on; done


# workspace 2 (file)
declare -a filem=(Thunar Pcmanfm ranger mc)
for i in ${filem[@]}; do
    bspc rule -a $i desktop='^2' follow=on focus=on; done

# workspace 3 (text)
declare -a code=(Code Geany emacs nvim neovim)
for i in ${code[@]}; do
    bspc rule -a $i desktop='^3' follow=on focus=on; done

# workspace 4 (media)
declare -a media=(vlc mpv mplayer ario)
for i in ${media[@]}; do
    bspc rule -a $i desktop='^4' follow=on focus=on; done

# workspace 5 (game)
declare -a games=(steam epic-game-store valheim game-launcher wine)
for i in ${games[@]}; do
    bspc rule -a $i desktop='^5' follow=on focus=on; done

# workspace 6 (sys)
#declare -a terminal=(Alacritty Xfce4-terminal urxvt)
#for i in ${terminal[@]}; do
#    bspc rule -a $i desktop='^6' follow=on focus=on; done
declare -a settings=(GParted Lxappearance Arandr Pavucontrol Xfce4-settings-manager Font-manager Arcolinux-tweak-tool.py rofi)
for i in ${settings[@]}; do
    bspc rule -a $i desktop='^6' follow=on focus=on; done

# floating windows
declare -a floats=(Lxappearance Arandr feh Arcolinux-tweak-tool.py Arcolinux-welcome-app.py Arcolinux-calamares-tool.py mpv  \
Font-manager Galculator Oblogout Pavucontrol rofi Xfce4-terminal Alacritty gcolor3 Gcolor3)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done


###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window
