#!/usr/bin/env bash
##   _______  _______ _______ ___ ___ ___ ___
##  |   _   \|   _   |   _   |   Y   |   Y   |
##  |.  1   /|   1___|.  1   |.  |   |.      |
##  |.  _   \|____   |.  ____|. / \  |. \_/  |
##  |:  1    |:  1   |:  |   |:      |:  |   |
##  |::.. .  |::.. . |::.|   |::.|:. |::.|:. |
##  `-------'`-------`---'   `--- ---`--- ---'
##	Stand: 10.04.22

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh

## Java Applications
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
	ALTRED=$(xrdb -query | grep 'color9:'| awk '{print $NF}')
	ALTBLACK=$(xrdb -query | grep 'color8:'| awk '{print $NF}')
	}
getcolors

## Configurations --------------------------------------------#
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		#bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'
		#bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' ''
		bspc monitor ${monitor} -n "$name" -d 'web' 'file' 'text' 'media' 'game' 'sys'
		let name++
	done
}
workspaces

bspc config border_width 1
bspc config window_gap 5
bspc config split_ratio 0.52

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

#BSPWM coloring
bspc config focused_border_color "$ALTRED" 
bspc config normal_border_color "$ALTBLACK"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

# 1 > terminal
bspc rule -a Alacritty desktop='^6' follow=on focus=on
bspc rule -a Xfce4-terminal desktop='^6' follow=on focus=on

# 2 > web
bspc rule -a firefox desktop='^1' follow=on focus=on
bspc rule -a chromium desktop='^1' follow=on focus=on

# 3 > files
declare -a files=(Pcmanfm Thunar qBittorrent)
for i in ${files[@]}; do
   bspc rule -a $i desktop='^2' follow=on focus=on; done

# 4 > code
declare -a code=(Geany code-oss)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done

# 5 > office and docs
declare -a office=(Gucharmap Atril Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done

# 6 > Communication
declare -a comm=(Thunderbird TelegramDesktop Hexchat)
for i in ${comm[@]}; do
   bspc rule -a $i desktop='^1' follow=on focus=on; done

# 7 > media
declare -a media=(Audacity Music MPlayer Lxmusic Inkscape Gimp-2.10 obs)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^4' state=floating follow=on focus=on; done

# 8 > settings
bspc rule -a 'VirtualBox Manager' desktop='^6' follow=on focus=on
bspc rule -a GParted desktop='^6' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^6' state=floating follow=on focus=on; done

# special rules
declare -a floating=(alacritty-float  Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off
