#!/usr/bin/env bash
##   _______  _______ _______ ___ ___ ___ ___
##  |   _   \|   _   |   _   |   Y   |   Y   |
##  |.  1   /|   1___|.  1   |.  |   |.      |
##  |.  _   \|____   |.  ____|. / \  |. \_/  |
##  |:  1    |:  1   |:  |   |:      |:  |   |
##  |::.. .  |::.. . |::.|   |::.|:. |::.|:. |
##  `-------'`-------`---'   `--- ---`--- ---'
##	Stand: 10.04.22

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh

## Java Applications
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
	ALTRED=$(xrdb -query | grep 'color9:'| awk '{print $NF}')
	ALTBLACK=$(xrdb -query | grep 'color8:'| awk '{print $NF}')
	}
getcolors

## Configurations --------------------------------------------#
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		#bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'
		#bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' ''
		bspc monitor ${monitor} -n "$name" -d 'web' 'file' 'text' 'media' 'game' 'sys'
		let name++
	done
}
workspaces

bspc config border_width 1
bspc config window_gap 5
bspc config split_ratio 0.52

bspc config top_padding          34
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

spc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config focused_border_color "$ALTRED" 
bspc config normal_border_color "$ALTBLACK"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

# workspace 1 (web)
declare -a web=(firefox)
for i in ${web[@]}; do
    bspc rule -a $i desktop='^1' follow=on focus=on; done
declare -a comm=(Thunderbird TelegramDesktop Bluemail)
for i in ${comm[@]}; do
   bspc rule -a $i desktop='^1' follow=on focus=on; done


# workspace 2 (file)
declare -a filem=(Thunar Pcmanfm ranger mc)
for i in ${filem[@]}; do
    bspc rule -a $i desktop='^2' follow=on focus=on; done

# workspace 3 (text)
declare -a code=(Code Geany emacs nvim neovim)
for i in ${code[@]}; do
    bspc rule -a $i desktop='^3' follow=on focus=on; done

# workspace 4 (media)
declare -a media=(vlc mpv mplayer ario)
for i in ${media[@]}; do
    bspc rule -a $i desktop='^4' follow=on focus=on; done

# workspace 5 (game)
declare -a games=(steam epic-game-store valheim game-launcher wine)
for i in ${games[@]}; do
    bspc rule -a $i desktop='^5' follow=on focus=on; done

# workspace 6 (sys)
#declare -a terminal=(Alacritty Xfce4-terminal urxvt)
#for i in ${terminal[@]}; do
#    bspc rule -a $i desktop='^6' follow=on focus=on; done
declare -a settings=(GParted Lxappearance Arandr Pavucontrol Xfce4-settings-manager Font-manager Arcolinux-tweak-tool.py rofi)
for i in ${settings[@]}; do
    bspc rule -a $i desktop='^6' follow=on focus=on; done

# floating windows
declare -a floats=(Lxappearance Arandr feh Arcolinux-tweak-tool.py Arcolinux-welcome-app.py Arcolinux-calamares-tool.py mpv  \
Font-manager Galculator Oblogout Pavucontrol rofi Xfce4-terminal Alacritty gcolor3 Gcolor3 urxvt URxvt)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done

