#! /usr/bin/env bash

### ALIASES ###
alias ggit="~/.dotfiles/up.sh"

#################################################################################
# vim and emacs
#alias vim="nvim"
alias emacs="emacsclient -c -a 'emacs'"
#alias doomsync="~/.config/emacs/bin/doom sync"
#alias doomdoctor="~/.emacs.d/bin/doom doctor"
#alias doomupgrade="~/.emacs.d/bin/doom upgrade"
#alias doompurge="~/.emacs.d/bin/doom purge"

#list (standard)
#alias ls='ls --color=auto'
#alias la='ls -a'
#alias ll='ls -alFh'
#alias l='ls'
#alias l.="ls -A | egrep '^\.'"

# EXA !!!!
alias lsa='exa -al --color=always --group-directories-first --icons' # my preferred listing
alias ls='exa  --color=always --group-directories-first --icons' # my preferred listing
alias la='exa -a --color=always --group-directories-first --icons'  # all files and dirs
alias ll='exa -l --color=always --group-directories-first --icons'  # long format
alias lt='exa -aT --color=always --group-directories-first --icons' # tree listing
alias l.='exa -a | egrep "^\."'
alias l='exa --color=always --icons'


# adding flags
alias df='df -h'                          # human-readable sizes
alias free='free -mt'                      # show sizes in MB

# git
#alias addup='git add -u'
#alias addall='git add .'
#alias branch='git branch'
#alias checkout='git checkout'
#alias clone='git clone'
#alias commit='git commit -m'
#alias fetch='git fetch'
alias pull='git pull origin'
#alias push='git push origin'
#alias stat='git status'  # 'status' is protected name so using 'stat' instead
#alias tag='git tag'
#alias newtag='git tag -a'

# gitpw
alias gpw="cat /home/distel/work/.meingithub"
